# 异常

执行中发生的异常事件：

1. Error（错误） Java虚拟机无法解决的严重问题，比如JVM内部错误，资源耗尽等严重错误，程序会崩溃
2. Exception（异常）因变成错误或偶然外在因素导致的一般性问题，可以使用针对性的代码进行处理。Exception分为两大类：运行时异常（程序运行时发生的异常） 编译时异常（编程时，编译器检查出的异常）

## 异常体系图

![image-20220316213222590](.\assets\image-20220316213222590.png)

## 异常类别

1. 运行时异常，编译器检查不出来，一般是变成时的逻辑错误，对于运行时异常，可以不做处理
2. 编译时异常，编译器要求必须处置的异常

## 常见运行时异常

1. NullPointerException：空指针异常
2. ArithmeticException：数学运算异常
3. ArrayIndexOutOfBoundsException：数组下标越界异常
4. ClassCastException：类型转换异常
5. NumberFormatException：数字格式不正确异常，将字符串转换为目标类型时会抛出

## 异常处理

1. try-catch-finally :代码块中捕获异常，程序员自己处理

   1. try代码块可以有多个异常，可以用多个catch分别捕获，子类异常写在前面，父类异常写在后面

      ```java
      package com.ljd.trycatch_;
      
      import java.util.Scanner;
      
      public class TryCatch01 {
          public static void main(String[] args) {
              int n;
              while(true){
                  System.out.println("请输入一个整数");
                  Scanner scanner = new Scanner(System.in);
                  String next = scanner.next();
                  try {
                      n = Integer.parseInt(next);
                      break;
                  } catch (NumberFormatException e) {
                      System.out.println("输入的不是整数");
                  }
              }
              System.out.println("输入的整数为:" + n);
          }
      }
      ```

2. throws：在方法中将发生的异常抛出，交给方法的调用者处理，最顶级的处理者就是JVM

   1. 子类重写父类的方法，抛出异常不能扩大异常范围
   2. java中并不要求程序员显式处理运行异常，因为有默认处理机制，默认抛出，throws抛出运行异常在方法外可以不处理

## 自定义异常

1. 定义类：自定义异常名，继承Exception 或 RuntimeException
2. 如果继承Exception，属于编译异常
3. 如果继承RuntimeExcepton 属于运行异常（一般使用运行时异常）
4. 使用throw关键字抛出异常

### 例子

```java
package com.ljd.exception_;

public class CustomeException01 {
    public static void main(String[] args) {
        int age = 8;
        if(!(age >=18 && age <=120)){
            //可以通过构造器设置信息
            throw new AgeException("年龄需要在 18~120 之间");
        }
        System.out.println("年龄正确");
    }
}
//自定义异常
//一般情况下，自定义异常继承RuntimeException
//好处是可以使用默认的异常处理机制
class AgeException extends RuntimeException{
    public AgeException(String message) {
        super(message);
    }

}
```

## throw 与 throws

throws：在方法声明处，表示抛出的异常的类型

throw：在方法体内，用于手动抛出异常对象